@baseUrl = http://localhost:3000
### Pesquisa todos os cursos
GET {{baseUrl}}/api/Poke

### Pesquisa curso específico
GET {{baseUrl}}/api/Poke/660dae17c3f2bdbad488ca58

### Pesquisa curso específico
POST {{baseUrl}}/api/Poke
Content-Type: application/json

{
"name": "Pikachu",
"species": "Eletrico",
"abilities": "Raio",
"hp": 2222,
"attack": 5556,
"defense": 8887,
"speed": 7771,
"number": 1
}

### Altera a conta com id=1
PUT {{baseUrl}}/api/Poke/660dae17c3f2bdbad488ca58
Content-Type: application/json

{
"number": 1
}

### Exclui uma conta específica
DELETE {{baseUrl}}/api/Poke/66077424818852eececedcff